name: validate-release-plan
description: |
  Validates release-plan.yaml files against the CAMARA release plan schema.
  Performs schema validation and semantic checks (API status consistency, etc.).

inputs:
  release_plan_path:
    description: 'Path to the release-plan.yaml file'
    required: true
    default: 'release-plan.yaml'
  schema_path:
    description: 'Path to schema file (optional, uses bundled schema if not specified)'
    required: false
  check_files:
    description: 'Check if referenced API files exist'
    required: false
    default: 'false'

outputs:
  valid:
    description: 'Whether validation passed (true/false)'
    value: ${{ steps.validate.outputs.valid }}
  errors:
    description: 'JSON array of error messages'
    value: ${{ steps.validate.outputs.errors }}
  warnings:
    description: 'JSON array of warning messages'
    value: ${{ steps.validate.outputs.warnings }}

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: pip install --quiet pyyaml jsonschema

    - name: Run validation
      id: validate
      shell: bash
      run: |
        set +e  # Don't exit on error - capture exit code

        SCRIPT_PATH="${{ github.action_path }}/../../validation/scripts/validate-release-plan.py"

        # Build command arguments
        ARGS="${{ inputs.release_plan_path }}"
        ARGS="$ARGS --type release-plan"

        if [[ -n "${{ inputs.schema_path }}" ]]; then
          ARGS="$ARGS --schema ${{ inputs.schema_path }}"
        fi

        if [[ "${{ inputs.check_files }}" == "true" ]]; then
          ARGS="$ARGS --check-files"
        fi

        echo "Running: python3 $SCRIPT_PATH $ARGS"

        # Run validation and capture output
        OUTPUT=$(python3 "$SCRIPT_PATH" $ARGS 2>&1)
        EXIT_CODE=$?

        echo "$OUTPUT"

        # Parse output for errors and warnings
        # Extract lines containing "ERROR:" and "WARNING:"
        ERRORS=$(echo "$OUTPUT" | grep "ERROR:" | sed 's/^.*ERROR: //' | jq -R -s 'split("\n") | map(select(length > 0))')
        WARNINGS=$(echo "$OUTPUT" | grep "WARNING:" | sed 's/^.*WARNING: //' | jq -R -s 'split("\n") | map(select(length > 0))')

        # Default to empty arrays if no matches
        if [[ -z "$ERRORS" ]]; then
          ERRORS="[]"
        fi
        if [[ -z "$WARNINGS" ]]; then
          WARNINGS="[]"
        fi

        # Set outputs
        if [[ $EXIT_CODE -eq 0 ]]; then
          echo "valid=true" >> $GITHUB_OUTPUT
        else
          echo "valid=false" >> $GITHUB_OUTPUT
        fi

        # Use heredoc for JSON arrays to handle special characters
        {
          echo 'errors<<ERRORS_EOF'
          echo "$ERRORS"
          echo 'ERRORS_EOF'
        } >> $GITHUB_OUTPUT

        {
          echo 'warnings<<WARNINGS_EOF'
          echo "$WARNINGS"
          echo 'WARNINGS_EOF'
        } >> $GITHUB_OUTPUT

        exit $EXIT_CODE
