# .github/workflows/pr-files-analyzer.yml
name: PR Analyzer

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_url:
        description: 'Pull Request URL (e.g., https://github.com/owner/repo/pull/123)'
        required: true
        type: string
      issue_number:
        description: 'Issue number to update'
        required: true
        type: string

permissions:
  issues: write
  contents: read
  pull-requests: read

jobs:
  analyze-pr-files:
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR info from input or comment
        id: extract_pr
        run: |
          # Function to extract PR info from URL
          extract_pr_info() {
            local url="$1"
            # Extract owner, repo, and PR number from GitHub PR URL
            if [[ $url =~ https://github\.com/([^/]+)/([^/]+)/pull/([0-9]+) ]]; then
              echo "owner=${BASH_REMATCH[1]}"
              echo "repo=${BASH_REMATCH[2]}"
              echo "pr_number=${BASH_REMATCH[3]}"
              echo "valid=true"
            else
              echo "valid=false"
            fi
          }
          
          # Determine source of PR URL and issue number
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # Manual trigger
            PR_URL="${{ github.event.inputs.pr_url }}"
            ISSUE_NUMBER="${{ github.event.inputs.issue_number }}"
          elif [ "${{ github.event_name }}" == "issue_comment" ]; then
            # Comment trigger - look for PR URL in comment
            COMMENT_BODY="${{ github.event.comment.body }}"
            PR_URL=$(echo "$COMMENT_BODY" | grep -oP 'https://github\.com/[^/]+/[^/]+/pull/[0-9]+' | head -1)
            ISSUE_NUMBER="${{ github.event.issue.number }}"
            
            # Only proceed if comment contains "/analyze-pr" command
            if [[ ! "$COMMENT_BODY" =~ /analyze-pr ]]; then
              echo "Comment doesn't contain /analyze-pr command, skipping..."
              echo "skip=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          else
            # Issue opened/labeled - look for PR URL in issue body
            ISSUE_BODY="${{ github.event.issue.body }}"
            PR_URL=$(echo "$ISSUE_BODY" | grep -oP 'https://github\.com/[^/]+/[^/]+/pull/[0-9]+' | head -1)
            ISSUE_NUMBER="${{ github.event.issue.number }}"
          fi
          
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          
          if [ -z "$PR_URL" ]; then
            echo "No PR URL found, skipping..."
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
          
          # Extract PR information
          eval $(extract_pr_info "$PR_URL")
          
          if [ "$valid" != "true" ]; then
            echo "Invalid PR URL format: $PR_URL"
            echo "error=Invalid PR URL format" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "pr_owner=$owner" >> $GITHUB_OUTPUT
          echo "pr_repo=$repo" >> $GITHUB_OUTPUT
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
          echo "Skip: false, PR: $owner/$repo#$pr_number, Issue: $ISSUE_NUMBER"

      - name: Get PR details and files
        if: steps.extract_pr.outputs.skip != 'true' && steps.extract_pr.outputs.error == ''
        id: pr_details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_OWNER="${{ steps.extract_pr.outputs.pr_owner }}"
          PR_REPO="${{ steps.extract_pr.outputs.pr_repo }}"
          PR_NUMBER="${{ steps.extract_pr.outputs.pr_number }}"
          
          # Get PR details
          PR_DATA=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$PR_OWNER/$PR_REPO/pulls/$PR_NUMBER")
          
          # Check if PR exists
          if echo "$PR_DATA" | jq -e '.message == "Not Found"' > /dev/null; then
            echo "error=PR not found or not accessible" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo $PR_DATA

          # Extract PR info
          PR_TITLE=$(echo "$PR_DATA" | jq -r '.title')
          PR_STATE=$(echo "$PR_DATA" | jq -r '.state')
          PR_AUTHOR=$(echo "$PR_DATA" | jq -r '.user.login')
          PR_BRANCH=$(echo "$PR_DATA" | jq -r '.head.ref')
          PR_BASE=$(echo "$PR_DATA" | jq -r '.base.ref')
          PR_CREATED=$(echo "$PR_DATA" | jq -r '.created_at')
          PR_UPDATED=$(echo "$PR_DATA" | jq -r '.updated_at')
          ADDITIONS=$(echo "$PR_DATA" | jq -r '.additions')
          DELETIONS=$(echo "$PR_DATA" | jq -r '.deletions')
          CHANGED_FILES_COUNT=$(echo "$PR_DATA" | jq -r '.changed_files')
          
          # Get list of changed files
          FILES_DATA=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$PR_OWNER/$PR_REPO/pulls/$PR_NUMBER/files")
          echo $FILES_DATA

                    
          # Process files data
          FILES_LIST=""
          FILE_STATS=""
          
          while IFS= read -r file; do
            filename=$(echo "$file" | jq -r '.filename')
            status=$(echo "$file" | jq -r '.status')
            additions=$(echo "$file" | jq -r '.additions')
            deletions=$(echo "$file" | jq -r '.deletions')
            changes=$(echo "$file" | jq -r '.changes')
            
            # Determine emoji based on file status
            case $status in
              "added") emoji="🆕" ;;
              "removed") emoji="🗑️" ;;
              "modified") emoji="📝" ;;
              "renamed") emoji="🔄" ;;
              *) emoji="📄" ;;
            esac
            
            FILES_LIST+="$emoji \`$filename\` ($status: +$additions/-$deletions)

            # Collect file extension stats
            ext="${filename##*.}"
            if [ "$ext" != "$filename" ]; then
              FILE_STATS+="$ext "
            fi
          done < <(echo "$FILES_DATA" | jq -c '.[]')

          
          echo $FILES_LIST
          echo $FILES_STAT
